export const BASE = {
  ADENINE: { name: "adenine", color: "#601A4A" },
  THYMINE: { name: "thymine", color: "#EE442F" },
  GUANINE: { name: "guanine", color: "#63ACBE" },
  CYTOSINE: { name: "cytosine", color: "#F9F4EC" },
};

// specify only top half of the base pair, in groups of 5
export const BASE_PAIRS = [
  [BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.ADENINE, BASE.CYTOSINE],
  [BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.ADENINE, BASE.CYTOSINE],
  [BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.ADENINE, BASE.CYTOSINE],
  [BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.ADENINE, BASE.CYTOSINE],
  [BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.ADENINE, BASE.CYTOSINE],
  [BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.ADENINE, BASE.CYTOSINE],
];
