export const BASE = {
  ADENINE: { name: "adenine", color: 1, complement: 2 },
  THYMINE: { name: "thymine", color: 2, complement: 1 },
  GUANINE: { name: "guanine", color: 3, complement: 4 },
  CYTOSINE: { name: "cytosine", color: 4, complement: 3 },
};

export const mutations = {
  3: "scaleColorGene",
  5: "tailShapeGene",
  15: "saltSpoutGene",
  18: "faceShapeGene",
  28: "backSpikesGene",
};

// specify only top half of the base pair, in groups of 5
//prettier-ignore
export const basePair1 = [
  BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.ADENINE, BASE.CYTOSINE,
  BASE.CYTOSINE, BASE.CYTOSINE, BASE.GUANINE, BASE.ADENINE, BASE.GUANINE,
  BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.ADENINE, BASE.CYTOSINE,
  BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.ADENINE, BASE.CYTOSINE,
  BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.ADENINE, BASE.CYTOSINE,
  BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.ADENINE, BASE.CYTOSINE,
];

//prettier-ignore
export const basePair2 = [
  BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.THYMINE, BASE.CYTOSINE,
  BASE.ADENINE, BASE.CYTOSINE, BASE.GUANINE, BASE.ADENINE, BASE.GUANINE,
  BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.ADENINE, BASE.CYTOSINE,
  BASE.GUANINE, BASE.THYMINE, BASE.GUANINE, BASE.THYMINE, BASE.CYTOSINE,
  BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.ADENINE, BASE.CYTOSINE,
  BASE.ADENINE, BASE.THYMINE, BASE.GUANINE, BASE.CYTOSINE, BASE.CYTOSINE,
  ];
